models:
  image: tp33/django
  external_links:
    - mysql:db
  volumes:
    - ./app:/app
  ports:
    - "8001:8000"
  command: bash -c "pip install djangorestframework && python /app/mmk2nh_cs4501/manage.py makemigrations helloworld &&  python /app/mmk2nh_cs4501/manage.py migrate helloworld && python /app/mmk2nh_cs4501/manage.py loaddata /app/mmk2nh_cs4501/db.json && mod_wsgi-express start-server --reload-on-changes --working-directory /app/mmk2nh_cs4501 /app/mmk2nh_cs4501/mmk2nh_cs4501/wsgi.py"
   #bash -c /app/build.sh

exp:
  image: tp33/django
  container_name: exp
  links:
    - models:models-api
  ports:
    - "8002:8000"
  volumes:
    - /app/exp:/app
  command: "mod_wsgi-express start-server --reload-on-changes stuff-exp/wsgi.py"

web:
  image: tp33/django
  container_name: web
  links:
    - exp:exp-api
  ports:
    - "8000:8000"
  volumes:
    - /app/web:/app
  command: "mod_wsgi-express start-server --reload-on-changes stuff-web/wsgi.py"