models:
  image: tp33/django
  external_links:
    - mysql:db
  volumes:
    - ./app:/app
  ports:
    - "8001:8000"
  command: bash -c "pip install djangorestframework && python /app/mmk2nh_cs4501/manage.py makemigrations helloworld && python /app/mmk2nh_cs4501/manage.py migrate helloworld && mod_wsgi-express start-server --reload-on-changes --working-directory /app/mmk2nh_cs4501 /app/mmk2nh_cs4501/mmk2nh_cs4501/wsgi.py"