models:
  image: tp33/django
  external_links:
    - mysql:db
  volumes:
    - ./cs4501team15:/app
  ports:
    - "8000:8000"
  command: bash -c "pip install djangorestframework && mod_wsgi-express start-server --working-directory ./cs4501team15 --reload-on-changes ./cs4501team15/app/mmk2nh_cs4501/mmk2nh_cs4501/wsgi.py"