# Generated by Django 2.1 on 2019-02-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_section', models.CharField(max_length=4)),
                ('course_is_lecture', models.BooleanField(default=True)),
                ('course_professor', models.CharField(max_length=200)),
                ('course_location', models.CharField(max_length=100)),
                ('course_days', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('course_start_time', models.DateTimeField()),
                ('course_end_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, to='accounts.Course'),
        ),
    ]
