# Generated by Django 2.1.7 on 2019-03-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_searching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_searching',
            field=models.BooleanField(),
        ),
    ]
