# Generated by Django 2.1 on 2019-03-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190303_1727'),
        ('accounts', '0002_auto_20190225_2240'),
    ]

    operations = [
    ]
