# Generated by Django 2.1 on 2019-03-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20190304_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='availability',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='home_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qualities',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_start_time',
            field=models.TimeField(),
        ),
    ]
