# Generated by Django 2.1.7 on 2019-03-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190304_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_description', models.CharField(default='', help_text='Enter a description about yourself.', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
    ]
