# Generated by Django 2.1 on 2019-03-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190304_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.AddField(
            model_name='customuser',
            name='availability',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='home_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qualities',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
