# Generated by Django 2.1 on 2019-03-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190304_2247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Class',
        ),
    ]
